import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavigationLayout from "@/components/layout/NavigationLayout";
import { ClerkProvider } from "@clerk/nextjs";

/**
 * Google Font Configuration
 *
 * To change the font throughout the entire app:
 * 1. Replace "Inter" with any Google Font name (e.g., "Roboto", "Poppins", "Open_Sans")
 * 2. Browse fonts at: https://fonts.google.com
 * 3. Save the file - that's it!
 *
 * Popular options:
 * - Inter (current) - Modern, clean, professional
 * - Roboto - Google's signature font
 * - Poppins - Geometric, friendly
 * - Open_Sans - Highly readable
 * - Montserrat - Bold, impactful
 * - Lato - Warm, friendly
 * - Source_Sans_3 - Clean, readable
 * - Work_Sans - Contemporary
 */
const appFont = Inter({
  variable: "--font-app",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${appFont.variable} antialiased`}>
          <NavigationLayout>
            {children}
          </NavigationLayout>
        </body>
      </html>
    </ClerkProvider>
  );
}
