import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import NavigationLayout from "@/components/Navigation/NavigationLayout";
import { ClerkProvider } from "@clerk/nextjs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} antialiased`}>
          <NavigationLayout>
            {children}
          </NavigationLayout>
        </body>
      </html>
    </ClerkProvider>
  );
}
